### ISSUE TITLE
Switch sides on a clock button press

### ISSUE THREAD

**Issue by ifekali** [jromang/picochess#82] opened 2015-05-23 00:25 UTC
This was implemented in old code, please re-implement at your convenience, it's a usefull feature.

When user presses FOURTH CLOCK BUTTON on his thinking time, picobot will switch sides and execute a move for user. This effectively switches sides as picobot is waiting for user move now. If button is pressed again, picobot switches sides again.

**Comment by LocutusOfPenguin** [comment] 2015-05-27 14:10
Today - without seeing this issue - i had the same idea.
But i implement it on 3rd button cause when computer is thinking, i want it to stop and play the move.

**Comment by ifekali** [comment] 2015-05-27 15:40
3rd button is even better, as it corresponds to usual play/pause button on the clock.

**Comment by LocutusOfPenguin** [comment] 2015-05-28 09:38
OK,
i updated this on my fork, made "position setup" working better, updated the docu.
I also made some source code modifications (cause i thinked, it been on wrong place).
But i cant test it on all hardware (for example no webserver, dt3000, ...). Can someone take a look?

**Comment by djdekker** [comment] 2015-05-28 14:23
I can confirm that switching sides with the 3rd clock button works fine now on my Pi2 with BT board and DGT3000 clock. Thank you! :)

**Comment by sshivaji** [comment] 2015-05-28 14:56
I have merged in the code change but will perhaps modify it to do the following:

1. Button 0 shows last move (already working)
2. Button 1 shows a hint or book move (to be done).
3. Button 2 switch sides (already working?).
4. Button 3 resigns?

Thanks for the pull!

Shiv

**Comment by sshivaji** [comment] 2015-05-28 15:10
Your change is now merged in. Thanks.

FYI, you can always start webserver mode by just starting picochess with a -w (you need to run as sudo because it broadcasts to port 80).

**Comment by LocutusOfPenguin** [comment] 2015-06-12 16:22
@sshivaji
pls close

**Comment by sshivaji** [comment] 2015-06-12 16:42
Sure, I can. @LocutusOfPenguin, you can close too if you believe the issue is resolved :)

**Closed by sshivaji** 2015-06-12 16:42 UTC
Labels: enhancement
