### ISSUE TITLE
NoneType Error in engine

### ISSUE THREAD

**Issue by LocutusOfPenguin** [jromang/picochess#133] opened 2015-09-03 05:50 UTC
Going to "engine" menu. Press one time fourth button and then middle button.
=> AttributeError happening at line 433.

I only have stockfish installed (1 engine).

**Comment by pablo2000** [comment] 2015-09-03 11:42
Jürgen 

Lastest push includes (I hope, although I haven't recreated the error exactly as you have it) a fix for this. Pls would you test and update.

**Comment by LocutusOfPenguin** [comment] 2015-09-04 06:06
Pablo

i know now why it fails. My engines folder is abit different as its excepted.

I have a "stockfish-6-linux" folder, with all the src's...., and so on.
And a LINK "stockfish" towards "stockfish-6-linux/stockfish". I like to have all at one place ;-)
And since its a testing-setup, i dont use picochess.ini at all.
Now, the program seems to load the dict name as a filename. At least, eng[0] saying so.

Perhaps y can only use FILES for the engines list, or i must move the src's out of engines/

Jürgen

**Comment by pablo2000** [comment] 2015-09-04 07:39
OK... so I just tried to replicate your setup: link to engine binary in a directory with sources present, no .ini file etc and the only time I could get it to reproduce the same error was when the link pointed to a file that was no longer there - i.e. leave the link in place but remove the file after startup then try to access it from the engine menu. 

I don't think the presence of the source is a problem, the link points to the binary not the folder and anyway the code knows to ignore any filename with a "." in it.

Is this perhaps related to file attributes/ownership. I always test using 'sudo' as the final installation runs the code as a service and so with root privilege, and also as all the folders in the distribution image have root ownership, and I always test in an 'end user' setup. 

P

**Comment by pablo2000** [comment] 2015-09-04 07:46
In any event, if this problem occurs the clock should not indicate success when there is clearly no engine at all present now..... 

Something wrong with my error handling for sure. :(

I'll get on that while we figure out whats happening with the linked file.

**Comment by LocutusOfPenguin** [comment] 2015-09-04 08:13
i start with picochess with:
-e engines/stockfish

but "stockfish" is a LINK to "engines/stockfish-6-linux/stockfish". That works at startup.
But it seems to me, your code scans the engines dir, and see a "stockfish-6-linux" (dir)
and falsely use that for the eng[0] var see lines around 4[2|3]x.

**Comment by pablo2000** [comment] 2015-09-04 08:57
ok... I have the problem now. Your hunch about files was right.

The issue isn't the link, or the binary. It's the presence of the subdirectory in the engines folder. The code checks for files containing "." which excludes git files, source etc. But it doesn't check whether the 'file' is actually a file or a directory. So it's trying to load the directory as an engine.

I'll put a fix in to check it - it would also happen with the books directory btw, but I guess no-one has done it there. I'll also improve the error handling, as the failure should be more graceful.

**Comment by LocutusOfPenguin** [comment] 2015-09-04 08:58
yep..that what i meant with:
"Perhaps y can only use FILES for the engines list"

**Comment by pablo2000** [comment] 2015-09-04 09:24
Yeah...I get your comment now. I thought you meant 'files' rather than 'links'. It never occurred to me until your last post that your 'stockfish-6-linux' directory was actually inside the engines folder, but as soon as you said that the lightbulb came on!

Anyway, that's dealt with now so it's all good. Just adding some better error handling too.

**Closed** 2015-09-07 06:03 UTC
