### ISSUE TITLE
move recognition while sliding a piece

### ISSUE THREAD

**Issue by lucasvdp** [jromang/picochess#171] opened 2016-04-06 09:22 UTC
When moving a piece to slowly the board detects the squares you pass over. When this is also a legal move picochess starts the engine. After you finish the move it still thinks you did move your for example rook only 2 squares in stead of 4.

how to reproduce:
from starting position move the pawn on e2 a bit to slow to e4, picochess anwers with two moves for black.

desired behavior:
As long as you have not moved the opponents piece you can still continue moving your piece to a different legal move. So when another legal move (with the same piece) is detected the engine should be restarted.

this could be implemented by enhancing the takeback search for searching for takeback + legal move.

**Comment by L0rdH4x0r** [comment] 2016-04-18 17:19
I don't think it makes sense to kinda slow down this process, cuz it'd rather hinder if you wanna play a rapid game. Instead, I'd suggest you to better lift your piece when you move! It's also better for your board not to leave any scratches ;)
The speed of recognition is move objective and differs from case to case!
Maybe in future it'd be possible to put a slider for configuration in the webend?

Cheers!

**Comment by LocutusOfPenguin** [comment] 2016-04-18 20:56
L0rdH4x0r:
There is sliding code inside. But the problem is, this doesnt work when the engine's move is quicker as yr sliding time (it only fixes when the engine is still thinking, while y finished with yr slow move). The problem mainly happening in the opening and y are moving the pieces very slowly (so mainly not in blitz)
For example, y play 1.e2-e4, but hold on e3. This e3 is a book move, and the engine will answer e3 with e5 internally in almost no time. The next move e3-e4 is also valid, and therefore y get another black move as answer. For picochess y moved 1.e3 e5 2.e4 => so a bug
Thats what lucas saying. The solution is - as he said - let it take back (internally) until the computer move is really done on board. Now this issue is only waiting for someone to really fix it :-)

**Comment by L0rdH4x0r** [comment] 2016-04-18 22:59
Whoo strange behavior that! I always lift any pieces, so i never ran into that ^^
But why does it do that? I mean you didn't play e5? Don't you validate if the response has been played on the board before you let pass another move? Maybe fen matching (board and executed game string) after each move should ensure _a little bit_ of "correctness"?
I wish i had time to view inside the code; maybe one day :D

**Comment by LocutusOfPenguin** [comment] 2016-07-06 08:12
fixed with v0.68

**Closed by LocutusOfPenguin** 2016-07-06 08:12 UTC
Labels: bug
