### ISSUE TITLE
Error occurs on every game: WARNING dgtserial - process_message: Clock ACK error (32, 0, 0, 0)

### ISSUE THREAD

**Issue by L0rdH4x0r** [jromang/picochess#142] opened 2015-10-10 16:16 UTC
Hi there!

I am getting an error on every game, where the clock is just showing 0.00 0.00 and i can keep on playing only if i guess the right move.
I then started picochess with debug log level and noticed the following error occurs every game:

```
WARNING dgtserial - process_message: Clock ACK error (32, 0, 0, 0)
```

The setup is DGT clock/board version 1.14/1.80 on PI2 in game mode rapid 10'

You can see full log here http://pastebin.com/ZK8K37z3
In line 519 clock error occurs. After this im blind every game if the move (in this case from line 516) is not displayed.

Maybe it would be possible to repeat sending after clock ack missed.

**Comment by clonfsp** [comment] 2015-11-20 16:04
Also happend with Clock ACK message ignored.

**Comment by sshivaji** [comment] 2015-11-20 16:35
Is this with the XL clock or the DGT 3000?

**Comment by clonfsp** [comment] 2015-11-20 18:02
It happens to me with XL clock. it is annoyed because make picochess unusable: it goes wrong in almost every game.
If I can help in something let me know.
thanks

**Comment by sshivaji** [comment] 2015-11-20 18:48
Can you open a github issue detailing your latest notes on the DGT XL clock
issues - https://github.com/jromang/picochess/issues

I will have a look this weekend.

Shiv

**Comment by clonfsp** [comment] 2015-11-20 22:16
Is it necesary a new issue? This thread is about it. Anyway I post here my thought, notes and logs posted at google group.
My impression is that picochess maybe dont serialize correctly the messages send to clock, and maybe a good point would be to re-send those messages returned with an ack error or an ack that it is ignores.

copied now:

yo (clonfsp cambiar) 	

16 de nov.

Traducir el mensaje al español  

Hello,

I am new to picochess. I bought a raspberry a weeks ago, and am quite happy. I thank for the efforts and the great work. Congratulations.

The best thing is I am adapting my engine so I can play with him in the board. My engine has personalities and elo adjustment. I have been able to play with him through picochess in a beta build. Meanwhile I am playing and testing all system with stockfish.

Unfortunately I have found a bug that is happening in every game (tested on 0.51 and 0.55), so I am unable to finish any game. I am playing an at a computer move, the clock "hangs" and shows "0:00 0:00" or "book" or a move and it does not show nothing more than that even if there are events.

Sometimes If I look at the log for the move and make in on the board, I can continue the game. Sometimes a takeback...... Anyway it is quite annoyed. Hope this can be solved, I can test anything and help in whatever I can. Maybe a "resend" the move to clock when the warning could solve the problem.....

I post the log for three situations where this is happening.

Best regards,
Fer

2015-11-15 19:51:21.479 DEBUG dgtinterface - run: Read dgt from queue: Dgt.CLOCK_STOP
2015-11-15 19:51:21.504 DEBUG dgtinterface - run: Read dgt from queue: Dgt.DISPLAY_MOVE
2015-11-15 19:51:21.505 DEBUG dgthardware - _display_on_dgt_xl:  c8g4 
2015-11-15 19:51:21.516 DEBUG dgtserial - send_command: ->DGT [DgtClk.DGT_CMD_CLOCK_SETNRUN], length:12
2015-11-15 19:51:21.517 DEBUG dgtinterface - run: Read dgt from queue: Dgt.LIGHT_SQUARES
2015-11-15 19:51:21.548 DEBUG dgtserial - send_command: DGT clock locked
2015-11-15 19:51:21.626 DEBUG uci - _reset_allow_score: score-lock stopped
2015-11-15 19:51:21.667 DEBUG dgtserial - read_message: <-DGT [DgtMsg.DGT_MSG_BWTIME], length:7
2015-11-15 19:51:21.679 DEBUG uci - _reset_allow_pv: pv-lock stopped
2015-11-15 19:51:21.699 INFO dgtserial - process_message: DGT clock time received (0, 4, 52) : (0, 4, 51)
2015-11-15 19:51:21.705 DEBUG dgtserial - process_message: DGT clock unlocked
2015-11-15 19:51:21.711 DEBUG dgtserial - send_command: ->DGT [DgtClk.DGT_CMD_CLOCK_DISPLAY], length:13
2015-11-15 19:51:21.712 DEBUG dgtserial - send_command: DGT clock locked
2015-11-15 19:51:22.30 DEBUG dgtserial - read_message: <-DGT [DgtMsg.DGT_MSG_BWTIME], length:7
2015-11-15 19:51:22.37 WARNING dgtserial - process_message: Clock ACK error (32, 0, 0, 0)
2015-11-15 19:51:22.614 DEBUG dgtserial - read_message: <-DGT [DgtMsg.DGT_MSG_BWTIME], length:7
2015-11-15 19:51:22.621 DEBUG dgtserial - process_message: DGT clock message ignored
2015-11-15 19:51:22.622 DEBUG dgtserial - process_message: DGT clock unlocked

2015-11-15 19:55:10.796 DEBUG uci - on_line_received: <PopenProcess at 0x74f4db30 (pid=2567)> >> bestmove b6c4 ponder e3f2
2015-11-15 19:55:10.800 DEBUG picochess - main: Received event in event loop : Event.BEST_MOVE
2015-11-15 19:55:10.805 DEBUG dgtdisplay - run: Read message from queue: Message.SEARCH_STOPPED
2015-11-15 19:55:10.806 DEBUG dgtdisplay - run: Search stopped
2015-11-15 19:55:10.812 DEBUG dgtdisplay - run: Read message from queue: Message.STOP_CLOCK
2015-11-15 19:55:10.841 DEBUG dgtdisplay - run: Read message from queue: Message.COMPUTER_MOVE
2015-11-15 19:55:10.856 DEBUG dgtinterface - run: Read dgt from queue: Dgt.CLOCK_STOP
2015-11-15 19:55:10.857 DEBUG dgtinterface - run: Read dgt from queue: Dgt.DISPLAY_MOVE
2015-11-15 19:55:10.858 DEBUG dgthardware - _display_on_dgt_xl:  b6c4 
2015-11-15 19:55:10.859 DEBUG dgtserial - send_command: ->DGT [DgtClk.DGT_CMD_CLOCK_SETNRUN], length:12
2015-11-15 19:55:10.894 DEBUG dgtinterface - run: Read dgt from queue: Dgt.LIGHT_SQUARES
2015-11-15 19:55:10.916 DEBUG dgtserial - read_message: <-DGT [DgtMsg.DGT_MSG_BWTIME], length:7
2015-11-15 19:55:10.931 DEBUG dgtserial - send_command: DGT clock locked
2015-11-15 19:55:10.940 DEBUG uci - _reset_allow_score: score-lock stopped
2015-11-15 19:55:10.951 INFO dgtserial - process_message: DGT clock time received (0, 4, 25) : (0, 4, 39)
2015-11-15 19:55:10.983 DEBUG dgtserial - process_message: DGT clock unlocked
2015-11-15 19:55:11.16 DEBUG uci - _reset_allow_pv: pv-lock stopped
2015-11-15 19:55:11.16 DEBUG dgtserial - send_command: ->DGT [DgtClk.DGT_CMD_CLOCK_DISPLAY], length:13
2015-11-15 19:55:11.57 DEBUG dgtserial - send_command: DGT clock locked
2015-11-15 19:55:11.418 DEBUG dgtserial - read_message: <-DGT [DgtMsg.DGT_MSG_BWTIME], length:7
2015-11-15 19:55:11.425 WARNING dgtserial - process_message: Clock ACK error (32, 0, 0, 0)
2015-11-15 19:55:11.963 DEBUG dgtserial - read_message: <-DGT [DgtMsg.DGT_MSG_BWTIME], length:7
2015-11-15 19:55:12.347 DEBUG dgtserial - process_message: DGT clock message ignored
2015-11-15 19:55:12.352 DEBUG dgtserial - process_message: DGT clock unlocked

2015-11-16 08:42:06.200 DEBUG uci - _allow_fire_pv: pv-lock started
2015-11-16 08:42:06.202 DEBUG picochess - main: Received event in event loop : Event.NEW_PV
2015-11-16 08:42:06.207 DEBUG picochess - main: Received event in event loop : Event.BEST_MOVE
2015-11-16 08:42:06.208 DEBUG dgtdisplay - run: Read message from queue: Message.SEARCH_STOPPED
2015-11-16 08:42:06.219 DEBUG dgtdisplay - run: Search stopped
2015-11-16 08:42:06.225 DEBUG dgtdisplay - run: Read message from queue: Message.STOP_CLOCK
2015-11-16 08:42:06.241 DEBUG dgtinterface - run: Read dgt from queue: Dgt.CLOCK_STOP
2015-11-16 08:42:06.254 DEBUG dgtserial - send_command: ->DGT [Clock.DGT_CMD_CLOCK_SETNRUN], length:12
2015-11-16 08:42:06.255 DEBUG dgtserial - send_command: DGT clock locked
2015-11-16 08:42:06.332 DEBUG uci - _reset_allow_score: score-lock stopped
2015-11-16 08:42:06.349 DEBUG dgtserial - read_message: <-DGT [Messages.DGT_MSG_BWTIME], length:7
2015-11-16 08:42:06.355 INFO dgtserial - process_message: DGT clock time received (0, 3, 33) : (0, 2, 12)
2015-11-16 08:42:06.361 DEBUG dgtserial - process_message: DGT clock unlocked
2015-11-16 08:42:06.393 DEBUG dgtdisplay - run: Read message from queue: Message.COMPUTER_MOVE
2015-11-16 08:42:06.414 DEBUG uci - _reset_allow_pv: pv-lock stopped
2015-11-16 08:42:06.415 DEBUG dgtinterface - run: Read dgt from queue: Dgt.DISPLAY_MOVE
2015-11-16 08:42:06.441 DEBUG dgthardware - _display_on_dgt_xl:  f6d7 
2015-11-16 08:42:06.447 DEBUG dgtinterface - run: Read dgt from queue: Dgt.LIGHT_SQUARES
2015-11-16 08:42:06.453 DEBUG dgtserial - send_command: ->DGT [Clock.DGT_CMD_CLOCK_DISPLAY], length:13
2015-11-16 08:42:06.454 DEBUG dgtserial - send_command: DGT clock locked
2015-11-16 08:42:06.785 DEBUG dgtserial - read_message: <-DGT [Messages.DGT_MSG_BWTIME], length:7
2015-11-16 08:42:06.797 WARNING dgtserial - process_message: Clock ACK error (32, 0, 0, 0)
2015-11-16 08:42:07.318 DEBUG dgtserial - read_message: <-DGT [Messages.DGT_MSG_BWTIME], length:7
2015-11-16 08:42:07.325 DEBUG dgtserial - process_message: DGT clock message ignored
2015-11-16 08:42:07.326 DEBUG dgtserial - process_message: DGT clock unlocked
Haz clic aquí para responder



Axel 	

17 de nov.

Traducir el mensaje al español  

Hi,

I have the same or a similar problem. My XL Clock does not work together with version 0.51. The clock only shows 0.00 0.00 or -- -- -- --. When I execute a move on the board, picochess responds, which I can see in the web interface. But the clock still shows the same. There is also no way to acess the menu from the clock.

I tried version 0.45 and it worked. Unfortunately the auto update gave rebirth to the problem... 

I would appreciate any hints!

Thank you in advance.

Best regards
Axel
- mostrar texto citado -
 


yo (clonfsp cambiar) 	

18 de nov.

Traducir el mensaje al español  

Hello:
I have investigated a bit more. I also have DGT XL clock. Please, be in mind that my understanding of the structure of the app is limited and maybe I am saying silly thing, sorre beforehand. These are only observations that could point to the cause.

1) For me 0.45 also has the problem, but happend less.

2) Sometimes is not the move what is wrong processed, but the send time command. I.e., I move, engine start thinging, picochess chess send time to clock, it shows 0:00-0:00, but engine moves and then picochess send the move to clock and it is correctly show.

3) The error happens always by one of two reasons, seeing at the log: Clock answer 'Clock ACK error' after display a move/time, or it return an ACK which is ignored (example posted at the end).
I dont know if this can help, but it looks in the example log posted that picochess send clock time information (DGT clock time received (0, 4, 50) : (0, 4, 53)) before it get the ACK from the clock of the display move command. I dont know if the lock is correctly handled, but maybe that could be the cause in any point in the code . Also 'send commands' that return wrong ack maybe should be resend to correctly show msg.

Thank yoy very much. Hope this information could help (and not be of more confussion :)

2015-11-18 20:11:03.858 DEBUG dgtdisplay - run: Read message from queue: Message.COMPUTER_MOVE
2015-11-18 20:11:03.867 DEBUG dgtinterface - run: Read dgt from queue: Dgt.CLOCK_STOP
2015-11-18 20:11:03.884 DEBUG dgtinterface - run: Read dgt from queue: Dgt.DISPLAY_MOVE
2015-11-18 20:11:03.886 DEBUG dgthardware - _display_on_dgt_xl:  d8b6 
2015-11-18 20:11:03.931 DEBUG dgtinterface - run: Read dgt from queue: Dgt.LIGHT_SQUARES
2015-11-18 20:11:03.932 DEBUG dgtserial - send_command: ->DGT [DgtClk.DGT_CMD_CLOCK_SETNRUN], length:12
2015-11-18 20:11:03.999 DEBUG dgtserial - send_command: DGT clock locked
2015-11-18 20:11:04.64 DEBUG dgtserial - read_message: <-DGT [DgtMsg.DGT_MSG_BWTIME], length:7
2015-11-18 20:11:04.81 INFO dgtserial - process_message: DGT clock time received (0, 4, 50) : (0, 4, 53)
2015-11-18 20:11:04.88 DEBUG dgtserial - process_message: DGT clock unlocked
2015-11-18 20:11:04.99 DEBUG dgtserial - send_command: ->DGT [DgtClk.DGT_CMD_CLOCK_DISPLAY], length:13
2015-11-18 20:11:04.100 DEBUG dgtserial - send_command: DGT clock locked
2015-11-18 20:11:04.525 DEBUG dgtserial - read_message: <-DGT [DgtMsg.DGT_MSG_BWTIME], length:7
2015-11-18 20:11:04.539 WARNING dgtserial - process_message: Clock ACK error (32, 0, 0, 0)
2015-11-18 20:11:05.89 DEBUG dgtserial - read_message: <-DGT [DgtMsg.DGT_MSG_BWTIME], length:7
2015-11-18 20:11:05.111 DEBUG dgtserial - process_message: DGT clock message ignored
2015-11-18 20:11:05.118 DEBUG dgtserial - process_message: DGT clock unlocked
 
 


Axel 	

19 de nov.

Traducir el mensaje al español  

Hi together,

I am still a newbe to raspberry pi and picochess (and even to Linux / Debian), but I investigated a somehow similar problem.



With version 0.51 and 0.55 the clock does work properly and just displays 0:00 0:00 or -- -- -- -- .



I solved it unconventionally: I started picochess in any position but the start position (e.g. I put the knights to f3 and f6). Then the display shows the right version (pico 0.55) and when I put the pieces to the right places (g1 and g8) voilà: my dgt xl clock shows "New Game"!



Maybe this can help.



Best regards
Axel


Am Montag, 16. November 2015 10:27:05 UTC+1 schrieb clonfsp:
- mostrar texto citado -

**Comment by L0rdH4x0r** [comment] 2015-11-22 10:41
Yeah I can confirm it, it's happening with the DGT XL clock!

As already mentioned above, I would agree to have a threshold of lets say 3 times where I would just try to resend the last command which went wrong.

I have not studied the source code in detail yet, but what I observed is that the clock is mostly showing 0.00 - 0.00 before it is showing the opponents move. And that's maybe the point where it is hanging then. Is it a "stop timer" command before issuing the "show move" command? Maybe both commands are sent too fast one after another? To prevent this it could help to add/increase some dummy busy waiting in between, what is just an idea. I think you'll get it right, great job so far! :+1:

**Comment by clonfsp** [comment] 2015-11-25 20:56
Hi Shiv,
could you see the issue during the weekend? any ideas'
best regards,

**Comment by sshivaji** [comment] 2015-12-02 09:16
Just looked at it and did a quick fix for the DGT XL clock. Can you try
from master now?

Thanks, Shiv

**Comment by clonfsp** [comment] 2015-12-02 12:39
Thanks!!!

I will try to test it whenever I can and my work let me :) , and let you
know.

regards




------------------------------
*Fermín Serrano*


2015-12-02 10:16 GMT+01:00 Shivkumar Shivaji <notifications@github.com>:

**Comment by clonfsp** [comment] 2015-12-06 20:27
Hello Shiv

I have cloned master branch, turn on log and play a game. The problem is stil there after 15 or 20 moves. I copy the log. I suspect messages must be serialized and repeated if error. No other messages should be send if clock return error.

Hope you can find a fix... I am sad :( 

Thanks for your support


2015-12-06 21:20:43.734 DEBUG dgtdisplay - run: Read message from queue: Message.COMPUTER_MOVE
2015-12-06 21:20:43.746 DEBUG dgtserial - read_message: <-DGT [DgtMsg.DGT_MSG_BWTIME], length:7
2015-12-06 21:20:43.755 DEBUG dgtinterface - run: Read dgt from queue: Dgt.CLOCK_STOP
2015-12-06 21:20:43.803 DEBUG dgtinterface - run: Read dgt from queue: Dgt.DISPLAY_MOVE
2015-12-06 21:20:43.809 DEBUG dgthardware - _display_on_dgt_xl:  d4e3
2015-12-06 21:20:43.815 DEBUG dgtinterface - run: Read dgt from queue: Dgt.LIGHT_SQUARES
2015-12-06 21:20:43.822 DEBUG dgtserial - send_command: ->DGT [DgtClk.DGT_CMD_CLOCK_SETNRUN], length:12
2015-12-06 21:20:43.828 DEBUG dgtserial - send_command: DGT clock locked
2015-12-06 21:20:43.844 DEBUG uci - _reset_allow_score: score-lock stopped
2015-12-06 21:20:43.845 INFO dgtserial - process_message: DGT clock time received (0, 3, 7) : (0, 3, 38)
2015-12-06 21:20:43.917 DEBUG dgtserial - process_message: DGT clock unlocked
2015-12-06 21:20:43.901 DEBUG uci - _reset_allow_pv: pv-lock stopped
2015-12-06 21:20:43.924 DEBUG dgtserial - send_command: ->DGT [DgtClk.DGT_CMD_CLOCK_DISPLAY], length:13
2015-12-06 21:20:43.951 DEBUG dgtserial - send_command: DGT clock locked
2015-12-06 21:20:44.292 DEBUG dgtserial - read_message: <-DGT [DgtMsg.DGT_MSG_BWTIME], length:7
2015-12-06 21:20:44.299 WARNING dgtserial - process_message: Clock ACK error (32, 0, 0, 0)
2015-12-06 21:20:44.871 DEBUG dgtserial - read_message: <-DGT [DgtMsg.DGT_MSG_BWTIME], length:7
2015-12-06 21:20:44.878 DEBUG dgtserial - process_message: DGT clock message ignored
2015-12-06 21:20:44.879 DEBUG dgtserial - process_message: DGT clock unlocked

**Comment by sshivaji** [comment] 2015-12-06 20:28
Will look. I usually use the DGT 3000 and thus dont test the XL that much.

Shiv

**Comment by L0rdH4x0r** [comment] 2015-12-06 20:29
Hello guys!
It seems to be worse now. The error message from above is gone, but the missbehavior still remains (moves are not shown) and another strange thing came up. After a few moves it blocks and refuses to let me play the displayed move. I can insure that I am playing very gently with an appropriate delay between placing pieces, observing debug messages and trying to repeat actions by taking back the position with no success. The only possibility is then to completely restart the service.
Thanks for commitment!

**Comment by sshivaji** [comment] 2015-12-06 20:36
Any exceptions in the log?

Shiv

**Comment by L0rdH4x0r** [comment] 2015-12-06 21:09
Here is the full screen session log:
http://pastebin.com/x74v1BDn
Problem move is Black Knight g8 to f6. Clock is staying locked.

**Comment by sshivaji** [comment] 2015-12-06 21:11
Can you try it from master branch?

**Comment by L0rdH4x0r** [comment] 2015-12-06 21:31
Hmm, now it is showing this import error
```
Traceback (most recent call last):
  File "/opt/picochess/picochess.py", line 22, in <module>
    import configargparse
ImportError: No module named 'configargparse'
```
and after installing pip and easy_install argparse and easy_install configargparse still getting the error.

**Comment by sshivaji** [comment] 2015-12-06 21:56
Follow the dockerfile at
https://github.com/jromang/picochess/blob/master/docker/Dockerfile to
prepare pip3.

The exact command is
"pip3 install -r picochess/requirements.txt"

I will release an image soon (either late today or tomorrow).

Shiv

**Comment by L0rdH4x0r** [comment] 2015-12-06 22:10
Holy..., thank you! I cant imagine i forgot the 3 in pip3 :D 
Nevertheless it throws an exception

http://pastebin.com/FZvhPBCU

**Comment by L0rdH4x0r** [comment] 2015-12-06 22:33
Back to the original error:
http://pastebin.com/VCp7zsWb

The clock stopped showing the time after move b7b6 and crashed finally with
```
2015-12-06 22:19:20.80 WARNING dgtserial - process_message: Clock ACK error (32, 0, 0, 0)
```

**Comment by L0rdH4x0r** [comment] 2015-12-08 11:23
Log for commited version 59cfdc2:
http://pastebin.com/izsQGPuv

The clock xl did not show the erroneous 0.00 0.00 anymore but instead, no engine move has been displayed and it went out of time until clock stopped with 0.00 4.47

You are definitelly on the right way, thank you!

**Comment by LocutusOfPenguin** [comment] 2015-12-08 17:47
i knew this won't fix it. Therefore i didn't say a word (here) ;-)
dgt doku only lists 0x40 not 0x20 (=32) error code...so, its abit strange.

Needs more looking.

**Comment by L0rdH4x0r** [comment] 2015-12-11 06:19
I figured out, commit 5a21adb (before refactoring) is best working for me.
I think i'll stick with this for a while. Won't say it hasn't got any bugs, but yeah... at least i can finish one game after another :+1: Ofc i'll be keeping track of ongoing progress and hopefully this issue may get closed.

**Comment by mixographer** [comment] 2015-12-17 06:23
I often get the ACK message. I'm using a Mac, and a USB DGT Board.

**Comment by clonfsp** [comment] 2015-12-21 12:17
I have just upgrade to 0.56 and play a game. Only ten moves and the problem with ack error continues:

2015-12-21 13:11:13.384 DEBUG dgtserial - send_command: ->DGT [DgtClk.DGT_CMD_CLOCK_DISPLAY], length:13
2015-12-21 13:11:13.385 DEBUG dgtserial - send_command: DGT clock locked
2015-12-21 13:11:13.423 DEBUG uci - _reset_allow_score: score-lock stopped
2015-12-21 13:11:13.479 DEBUG uci - _reset_allow_pv: pv-lock stopped
2015-12-21 13:11:13.833 DEBUG dgtserial - read_message: <-DGT [DgtMsg.DGT_MSG_BWTIME], length:7
2015-12-21 13:11:13.840 WARNING dgtserial - process_message: Clock ACK error (32, 0, 0, 0)
2015-12-21 13:11:14.377 DEBUG dgtserial - read_message: <-DGT [DgtMsg.DGT_MSG_BWTIME], length:7
2015-12-21 13:11:14.384 INFO dgtserial - process_message: DGT clock time received [0, 3, 40] : [0, 3, 57]
2015-12-21 13:11:14.385 DEBUG dgtdisplay - run: Read message from queue: Message.DGT_CLOCK_TIME
2015-12-21 13:11:14.387 DEBUG dgtinterface - run: Read dgt from queue: Dgt.CLOCK_TIME


Hope this can be fixed soon. I think is more important to stop new features and try to make an stable version.

best regards
fermin

**Comment by ifekali** [comment] 2015-12-21 13:56
Indeed. Somewhere along the way we lost touch with stability. For example, USB only board is not working on raspi for some time now ... looks like the FTDI driver is broken ...




> On 21. dec. 2015, at 13:17, clonfsp <notifications@github.com> wrote:
> 
>  I think is more important to stop new features and try to make an stable version

- 
Jonas Žnidaršič
jonas@jonas.si

**Comment by LocutusOfPenguin** [comment] 2016-01-22 09:32
The v0.58 will resend a failed command once again. See my 159 issue for details.

**Comment by LocutusOfPenguin** [comment] 2016-02-04 17:33
Is there still a problem or can this issue be closed?

**Comment by L0rdH4x0r** [comment] 2016-02-04 20:12
Nice,
I'll let you know during the next week, cuz I have no time to test it right now :/
Thanks for patience and satisfaction of my/our wants :)
I appreciate it a lot!

**Comment by clonfsp** [comment] 2016-02-07 18:07
Hi,
I have been trying to test this issue with 0.58, but I am unable to make picochess to work (see below). I would please ask to not close this issue until I can test it.
Any idea why I can not run 0.58?
Thanks

2016-02-07 18:55:50.776 DEBUG dgtserial - read_board_message: <-DGT board [DgtMsg.DGT_MSG_BWTIME], length 7
2016-02-07 18:56:12.675 DEBUG picochess - main: Starting picochess with DGT board on [/dev/ttyUSB0]
2016-02-07 18:56:12.682 DEBUG dgtserial - write_board_command: ->DGT board [DgtCmd.DGT_SEND_UPDATE_NICE], length 1
2016-02-07 18:56:12.683 DEBUG dgtserial - write_board_command: ->DGT board [DgtCmd.DGT_SEND_VERSION], length 1
2016-02-07 18:56:12.684 DEBUG dgtserial - write_board_command: ->DGT board [DgtCmd.DGT_SEND_BRD], length 1
2016-02-07 18:56:12.685 DEBUG dgtserial - write_board_command: ->DGT board [DgtClk.DGT_CMD_CLOCK_VERSION], length 5
2016-02-07 18:56:12.686 DEBUG dgtserial - write_board_command: DGT clock [ser]: locked
2016-02-07 18:56:12.688 DEBUG picochess - main: ChessTalker disabled
2016-02-07 18:56:13.377 DEBUG dgtserial - read_board_message: <-DGT board [DgtMsg.DGT_MSG_VERSION], length 2
2016-02-07 18:56:13.379 DEBUG dgtserial - process_board_message: DGT board version 1.80
2016-02-07 18:56:13.384 DEBUG dgtinterface - run: Read dgt from queue: DGT_DISPLAY_TEXT
2016-02-07 18:56:13.390 DEBUG dgtinterface - run: Showing text for 0.5 secs
2016-02-07 18:56:13.391 DEBUG dgthw - _display_on_dgt_xl: Clock (still) not found. Ignore [ok usb]
2016-02-07 18:56:13.685 DEBUG picochess - engine_startup: Loaded engine [Stockfish 091114]
2016-02-07 18:56:13.686 DEBUG picochess - engine_startup: Supported options [OptionMap({'Clear Hash': Option(name='Clear Hash', type='button', default='', min=None, m$
2016-02-07 18:56:13.888 DEBUG dgtinterface - stopped_timer: Clock not running - ignored duration

**Comment by LocutusOfPenguin** [comment] 2016-02-08 07:45
Hi clonfsp,
it seems y have an usb only board with XL-clock (and issues are mainly closed if no feedback or solved, don't worry). The program seems not recognize yr clock.

Can y provide the complete log file (perhaps also take a look at the web-interface)?
I guess, it is working internally, but y cant see anything on the clock - need to be checked (with log).

Maybe think about a flag "force-XL-is-there" for such special cases can be implemented (but before i want to be sure, its really working internally)?!?
Not the best idea, but it will work then.

Jürgen

**Comment by clonfsp** [comment] 2016-02-08 19:10
I will do that during this week when I have enought time. Anyway I have been using it with <= 0.55 with no problem (except the ack error), and picochess recognized well the clock and messages where displayed.

**Comment by L0rdH4x0r** [comment] 2016-02-10 14:38
Okay, here are my test results and what I did:

1. updated + upgraded system
2. pip3 install requirements, all met and okay
3. enabled debug and screensession-log printout
4. rebooted and started the service
5. tried to play a game:
  - starting with e2-e4 but nothing happened
  - set up starting position and put the extra queen on c4, then removed and again
  - tried with e2-e4
  - once again, nothing happened so i pressed the 5th clock button while keeping the pawn on e4
  - during the observations the clock mostly showed 5.00 on each side

here the full log http://pastebin.com/Lc0R2A8Z

**Comment by kblaubaer** [comment] 2016-02-20 08:51
Hi,
I've similar problems with the combination of serial DGT board and DGT XL clock in v0.58 - the board is recognized but not the clock...
Do you have similar problems with the serial DGT board in combination with the DGT 3000 clock?
Regards, Michael

**Comment by LocutusOfPenguin** [comment] 2016-02-22 08:05
This issue is made for some 32 ack error from XL clock.
I think, by resending last failed command this issue is closed, no?

Now we are talking about another problem - please use issue #162 for this.
Thanks,
Jürgen

**Comment by L0rdH4x0r** [comment] 2016-02-24 22:58
Yeah, refactor, close and ignore :+1: 

Just kidding! :D

**Comment by clonfsp** [comment] 2016-02-29 09:58
I have downloaded 0.59 to test this problem but my clock XL isnt recognized (usb board).
:(

**Closed** 2016-03-01 19:47 UTC
