### ISSUE TITLE
Play halts after few moves when using USB board

### ISSUE THREAD

**Issue by ifekali** [jromang/picochess#218] opened 2016-10-29 18:37 UTC
This is an old issue (I was away for some time, unable to contribute) and I find myself surprised it is not resolved yet ... I'm I the only one using USB board (I have both, USB & bluetooth boards) or am I the only one experiencing this issue with the USB board?

My setup is Pi 2 with DGT 3000 clock and DGT USB board. I am using the 0.75 image from repository, updated to 0.77.

After bootup, using no configuration file (no picochess.ini), the play halts after few moves, the clock is stuck after displaying the engine's move.

I can resume the play by disconnecting and reconnecting the clock via cable or turning it off and on again.

-Izmet

P. S. I'm back.

**Comment by Albireo54** [comment] 2016-11-03 12:30
I also experience this issue, both on the .75 & .77 versions, it is quite annoying but I am able to go ahead in the game pressing twice the clock lever ... I really hope that this bug will solved soon.
Luigi

**Comment by LocutusOfPenguin** [comment] 2016-11-03 13:33
Please provide the log file.
If y update to v0.78 (and enter your email credentials) you can email this directly to your email box (=new feature) or do it by hand with <0.78 (this version doesn't help y with this particular problem)

**Comment by Albireo54** [comment] 2016-11-03 13:38
Is the 0.78 release out ?

**Comment by LocutusOfPenguin** [comment] 2016-11-03 13:52
yep.. see here: https://github.com/jromang/picochess/releases
but do what is said there...(or NOT use voice system at all).

**Comment by Albireo54** [comment] 2016-11-03 14:43
just installed following your instructions but picochess do not work anymore ...

**Comment by LocutusOfPenguin** [comment] 2016-11-08 10:22
@ifekali 
Does it freeze, or can y press a button and it then runs again?
I also guess, y not see any error on console or log file, yes?

@Albireo54 
Do y use voice? If not, after (another) update does it work now?
=> the first version crushed, if y had a voice problem(!) no matter if y use it or not. The current version will run, as long y not use this voice function (speaking ONLY for "trouble install voice system").

If y want to use voice y may look at issue #219 for doing the same as i did to get a running system.

Jürgen

**Comment by Albireo54** [comment] 2016-11-08 10:44
The voice is Ok, tested both al & dgt the issues as I said, are randomly freezing the clock (I have to restart picochess from the console) & not return back to display time after display the engine move (I can go ahead pressing the clock lever twice) LuigiInviato dal mio dispositivo Huawei-------- Messaggio originale --------Oggetto: Re: [jromang/picochess] Play halts after few moves when using USB board (#218)Da: Jürgen Précour A: jromang/picochess CC: Albireo54 ,Mention @ifekali 
Does it freeze, or can y press a button and it then runs again?
I also guess, y not see any error on console or log file, yes?

@Albireo54 
Do y use voice? If not, after (another) update does it work now?
=> the first version crushed, if y had a voice problem(!) no matter if y use it or not. The current version will run, as long y not use this voice function (speaking ONLY for "trouble install voice system").

If y want to use voice y may look at issue #219 for doing the same as i did to get a running system.

Jürgen

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jromang/picochess","title":"jromang/picochess","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jromang/picochess"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LocutusOfPenguin in #218:  @ifekali \r\nDoes it freeze, or can y press a button and it then runs again?\r\nI also guess, y not see any error on console or log file, yes?\r\n\r\n@Albireo54 \r\nDo y use voice? If not, after (another) update does it work now?\r\n=\u003e the first version crushed, if y had a voice problem(!) no matter if y use it or not. The current version will run, as long y not use this voice function (speaking ONLY for \"trouble install voice system\").\r\n\r\nIf y want to use voice y may look at issue #219 for doing the same as i did to get a running system.\r\n\r\nJürgen"}],"action":{"name":"View Issue","url":"https://github.com/jromang/picochess/issues/218#issuecomment-259099521"}}}

**Comment by LocutusOfPenguin** [comment] 2016-11-08 11:05
Great @Albireo54 ... You should told me, y are the same person as on forum , haha.

For this "1/2 freeze" & release by button press....Thats my question to Jonas. I would expect the same on his system. I tested it this morning on MY system. But for me, it never stops...That makes me hard to find out, how to change the code to fix it. I dont want to run a watchdog doing what y have to do, to release a "waiting" state....That would solve it, but its ugly (and would hide the error = the cause).

**Comment by Albireo54** [comment] 2016-11-08 11:20
Yes I am the same persone of the forum. I can only say that in every game I get the issues I show you. LuigiInviato dal mio dispositivo Huawei-------- Messaggio originale --------Oggetto: Re: [jromang/picochess] Play halts after few moves when using USB board (#218)Da: Jürgen Précour A: jromang/picochess CC: Albireo54 ,Mention Great @Albireo54 ... You should told me, y are the same person as on forum , haha.

For this "1/2 freeze" & release by button press....Thats my question to Jonas. I would expect the same on his system. I tested it this morning on MY system. But for me, it never stops...That makes me hard to find out, how to change the code to fix it. I dont want to run a watchdog doing what y have to do, to release a "waiting" state....That would solve it, but its ugly (and would hide the error = the cause).

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jromang/picochess","title":"jromang/picochess","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jromang/picochess"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LocutusOfPenguin in #218: Great @Albireo54 ... You should told me, y are the same person as on forum , haha.\r\n\r\nFor this \"1/2 freeze\" \u0026 release by button press....Thats my question to Jonas. I would expect the same on his system. I tested it this morning on MY system. But for me, it never stops...That makes me hard to find out, how to change the code to fix it. I dont want to run a watchdog doing what y have to do, to release a \"waiting\" state....That would solve it, but its ugly (and would hide the error = the cause)."}],"action":{"name":"View Issue","url":"https://github.com/jromang/picochess/issues/218#issuecomment-259108754"}}}

**Comment by ScallyBag** [comment] 2016-11-09 16:58
Hi Jürgen,

I'm back from my cruise and have updated both my test & live systems to 0.78. I had a few issues with requirements but eventually got everything to update after reading issues others have had over the past couple of weeks.
Ok, I can hear the 2 voices, but the DGT voice says "twenty" not "new game", if I alter a setting I.e. Level or book etc, it's says "ok", "twenty".
But the worse is that the play freezes every game, it says part of my move then no more voice, the clock runs down to zero. I cannot reboot with queens, nor does the game reset on placing pieces back to original squares, I have to manually reboot, which means I don't get emails of the game or log file (new). It freezes every game, some times move 3 other times later etc... but always the same, partly says my move, then the computer clock runs down to zero & I can't do anything .....

I'm using my RPi3 and Rev II as you know...

Al.

**Comment by djdekker** [comment] 2016-11-09 17:28
Hi Al,
Good to see you back! I'm having exactly the same trouble here with RPi3 and voice output enabled: the computer stops responding at some random(?) point during every game while its clock runs down to zero. I was using headphones (haven't got speakers) and enabled your not loud yet stentorian voice ;)
DJ

**Comment by ScallyBag** [comment] 2016-11-09 17:37
Hi DJ, yes exactly the same, I'm using headphones too. I haven't tried disabling the voices (yes it's mine 😄) When the problem happens, my voice partly announces the move (Nd ... instead of (Nd3) then stops and the clock runs down to zero.  I just did a quick update today but have packed things away until probably Friday as I'm out tomorrow. Does it work without voices? (it's weird listening to my own) I'm no longer getting moves emailed to me, nor this new log email (do I have to enable something?)

Al.

**Comment by Albireo54** [comment] 2016-11-09 17:55
Hi Al,

that’s my problem too, sometimes the clock stop working and I have to press the clock lever to go ahead, sometimes freezes and I have to restart picochess from the console. Identical issue with the voice that I deactivated. For the moment I go back to the 0.77 release if I want to play some decent games, the only issue in 0.77 is the clock randomly stop working showing the last engine move without go back to the clock time.

Luigi

 

Da: Alan John Cooper [mailto:notifications@github.com] 
Inviato: mercoledì 9 novembre 2016 17:58
A: jromang/picochess <picochess@noreply.github.com>
Cc: Albireo54 <lvogli@tin.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [jromang/picochess] Play halts after few moves when using USB board (#218)

 

Hi Jürgen,

I'm back from my cruise and have updated both my test & live systems to 0.78. I had a few issues with requirements but eventually got everything to update after reading issues others have had over the past couple of weeks.
Ok, I can hear the 2 voices, but the DGT voice says "twenty" not "new game", if I alter a setting I.e. Level or book etc, it's says "ok", "twenty".
But the worse is that the play freezes every game, it says part of my move then no more voice, the clock runs down to zero. I cannot reboot with queens, nor does the game reset on placing pieces back to original squares, I have to manually reboot, which means I don't get emails of the game or log file (new). It freezes every game, some times move 3 other times later etc... but always the same, partly says my move, then the computer clock runs down to zero & I can't do anything .....

I'm using my RPi3 and Rev II as you know...

Al.

**Comment by LocutusOfPenguin** [comment] 2016-11-09 18:49
Hi Al,
well...the dgt sounds arent complete. Thats the reason y hear 20, 30 or something. Its IN THIS MOMENT needed to use "al" as computer voice or live with this strange sounds ;-)
So, that is normal...and will be easily be changed as soon i get complete voice files.

For yr problems with voice....hmmm...for me working, but now y can easily send me a log file. Please do that. I see, what problem picochess has (that even working, if yr Rasp frozen, cause y can restart it, play a few moves, and get the log file - which incl. the last 1Mb).

Jürgen

**Comment by ScallyBag** [comment] 2016-11-09 21:44
Jürgen, 

I've sent the log via email...

Al.

**Comment by ScallyBag** [comment] 2016-11-10 16:54
Hi Jürgen,

Did you get my email and log? v0.78 is totally unplayable, I'm back online tomorrow (Friday) when I will test v0.78 without voice, but by what I'm hearing it doesn't change any of the 'freezing'. I will then revert back to v0.77 and see if that still works, maybe some of the updates or something else has affected the latest update of PicoChess?

Al.

**Comment by LocutusOfPenguin** [comment] 2016-11-10 17:28
Hi Al,
yes, i got your file..but sadly it doesn't help me (not your fault, ha).

Im abit unhappy people tend to mix up voice & "waiting" => freeze.
There is a problem with "waiting" ...that looks like picochess has stopped...but actually, its waiting.
You can press a button, do something else, and it recovers.
I tried to explain this two days ago.

Something else is a possible freeze by voice (or at least the v078 sound system not working).
But since its based on voice i can only happening with v0.78 whereas the other is (perhaps) there in former releases too.

Both are bugs...but for me they are complete different.

Honestly, this voice issue is there for almost 1year...but i now wished i wouldnt have started to do it cause i only use the software from others but people always tell me, "not working" ;-) Nevertheless i still need some sounds from you, ha.

**Comment by ScallyBag** [comment] 2016-11-10 17:54
Hi Jürgen,

Ok, I'll text you via Skype tomorrow. I've never had 'freezing' problems before nor do I have buttons as no clock. I'm happy to test anything and to provide more voice samples. DJ & others have similar problems with v0.78, let's hope we can get this sorted soon. 

Cheers,

Al.

**Comment by ScallyBag** [comment] 2016-11-11 13:16
Hi Everyone, 

I just tested again, with my voice and DGT voice and Pico doesn't respond after a few moves, then I changed both voices to mine, the game lasted longer but became unresponsive again. I then commented out both voices (# in ini file) and have played several games without a problem, so somehow the voice additions are causing the unresponsiveness or 'freezing' affect ....

Al.

**Comment by LocutusOfPenguin** [comment] 2016-11-11 15:47
@Albireo54 
if y want y can try out some new software from me. You must clone MY branch again (same procedure as i told y on forum) and then say "git checkout dgt-test" in this (cloned) picochess folder.

Hope your "stuck" problem is solved ;-) If not, don't need to run alot of tests...Tell me the result, and maybe get the log file for me (if problem still there). thanks.

Jürgen

**Comment by Albireo54** [comment] 2016-11-11 18:44
Hi Jürgen,

I would like to thank you for this opportunity to test this great piece of software, I played 2 games, the 1st game with the default settings and all seems OK !!!

I played a 2nd game changing engine, book, time and the only issue was the well known “Player W” “Player B” issue because of the DGT3000 sending to Picochess a “phantom” twice clock lever pressing, if I correctly understand y statement.

Seems to me that the clock freeze was solved, I keep on testing further for a pair of days your software and I let y know if this is really true.

Have a great evening and thank you again  :)

Luigi

 

 

Da: Jürgen Précour [mailto:notifications@github.com] 
Inviato: venerdì 11 novembre 2016 16:48
A: jromang/picochess <picochess@noreply.github.com>
Cc: Albireo54 <lvogli@tin.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [jromang/picochess] Play halts after few moves when using USB board (#218)

 

@Albireo54 <https://github.com/Albireo54>  
if y want y can try out some new software from me. You must clone MY branch again (same procedure as i told y on forum) and then say "git checkout dgt-test" in this (cloned) picochess folder.

Hope your "stuck" problem is solved ;-) If not, don't need to run alot of tests...Tell me the result, and maybe get the log file for me (if problem still there). thanks.

Jürgen

**Comment by Albireo54** [comment] 2016-11-11 20:37
Hi Jürgen

I played the 3rd game and while the engine was thinking his 7.  …  O – O  move suddenly the clocks stop “clicking” without producing a move, I was able to go ahead pressing twice the clock lever.

I produce the log file and the .pgn of the game I interrupted, I hope this will help to understand what’s happen.

I go ahead with testing your new software.

Luigi

 

Da: Jürgen Précour [mailto:notifications@github.com] 
Inviato: venerdì 11 novembre 2016 16:48
A: jromang/picochess <picochess@noreply.github.com>
Cc: Albireo54 <lvogli@tin.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [jromang/picochess] Play halts after few moves when using USB board (#218)

 

 <https://github.com/Albireo54> @Albireo54 
if y want y can try out some new software from me. You must clone MY branch again (same procedure as i told y on forum) and then say "git checkout dgt-test" in this (cloned) picochess folder.

Hope your "stuck" problem is solved ;-) If not, don't need to run alot of tests...Tell me the result, and maybe get the log file for me (if problem still there). thanks.

Jürgen

**Comment by Albireo54** [comment] 2016-11-11 21:26
Hi Jürgen,

I played the 4th game and again the clock stop working (like 3rd game) while the engine was thinking his 24 move.

I press twice the clock lever to produce the log after waiting very much time (to be sure ..) and while I was setting my pieces Picochess shows 24. … Ng3 just because of the twice clock lever press.

Attached you’ll find the log file, the game.pgn file and a shot of the position.

Luigi

 

 

Da: Jürgen Précour [mailto:notifications@github.com] 
Inviato: venerdì 11 novembre 2016 16:48
A: jromang/picochess <picochess@noreply.github.com>
Cc: Albireo54 <lvogli@tin.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [jromang/picochess] Play halts after few moves when using USB board (#218)

 

@Albireo54 <https://github.com/Albireo54>  
if y want y can try out some new software from me. You must clone MY branch again (same procedure as i told y on forum) and then say "git checkout dgt-test" in this (cloned) picochess folder.

Hope your "stuck" problem is solved ;-) If not, don't need to run alot of tests...Tell me the result, and maybe get the log file for me (if problem still there). thanks.

Jürgen

**Comment by LocutusOfPenguin** [comment] 2016-11-11 21:33
Hi
There is no. attachment. Dont need further testing just the File. Thanks

**Comment by Albireo54** [comment] 2016-11-11 21:42
Hi Jürgen

I played the 5th game and the same issue occur ( three games in a row) with the clock stop “clicking” without producing a move on a DGT3000 clock display. 

This time I do not produce the log file :)

All the best.

Luigi

 

Da: Jürgen Précour [mailto:notifications@github.com] 
Inviato: venerdì 11 novembre 2016 16:48
A: jromang/picochess <picochess@noreply.github.com>
Cc: Albireo54 <lvogli@tin.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [jromang/picochess] Play halts after few moves when using USB board (#218)

 

@Albireo54 <https://github.com/Albireo54>  
if y want y can try out some new software from me. You must clone MY branch again (same procedure as i told y on forum) and then say "git checkout dgt-test" in this (cloned) picochess folder.

Hope your "stuck" problem is solved ;-) If not, don't need to run alot of tests...Tell me the result, and maybe get the log file for me (if problem still there). thanks.

Jürgen

**Comment by Albireo54** [comment] 2016-11-11 21:58
Hi Jurgen I attached the log file in the 2 previous email, I to produce also this log 

 

Da: Jürgen Précour [mailto:notifications@github.com] 
Inviato: venerdì 11 novembre 2016 22:33
A: jromang/picochess <picochess@noreply.github.com>
Cc: Albireo54 <lvogli@tin.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [jromang/picochess] Play halts after few moves when using USB board (#218)

 

Hi
There is no. attachment. Dont need further testing just the File. Thanks

**Comment by LocutusOfPenguin** [comment] 2016-11-12 09:05
Hi Luigi,

i didnt get any log files. Not here (prob. not working anyway) , nor by eMail.
Perhaps y can send them directly to my eMail box (like y did in past)

Jürgen

**Comment by Albireo54** [comment] 2016-11-12 10:21
Hi Jurgen just resent the emails with the attachments to your google blog “PicoChess” as new post “Testing Picochess v.078”

Since now no more freeze of the clock after displaying the engine move :) only Player W & Player B and the stop “clicking” of the clock as I wrote yesterday.

Have a great day.

Luigi

 

Da: Jürgen Précour [mailto:notifications@github.com] 
Inviato: sabato 12 novembre 2016 10:06
A: jromang/picochess <picochess@noreply.github.com>
Cc: Albireo54 <lvogli@tin.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [jromang/picochess] Play halts after few moves when using USB board (#218)

 

Hi Luigi,

i didnt get any log files. Not here (prob. not working anyway) , nor by eMail.
Perhaps y can send them directly to my eMail box (like y did in past)

Jürgen

**Comment by Albireo54** [comment] 2016-11-12 10:29
Hi Jürgen,

I forgot to say that the voice also works well (en:al) computer side, I would like to translate it into Italian if you agree and if you give me some hints.

Thank you.

Luigi

 

Da: Jürgen Précour [mailto:notifications@github.com] 
Inviato: sabato 12 novembre 2016 10:06
A: jromang/picochess <picochess@noreply.github.com>
Cc: Albireo54 <lvogli@tin.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [jromang/picochess] Play halts after few moves when using USB board (#218)

 

Hi Luigi,

i didnt get any log files. Not here (prob. not working anyway) , nor by eMail.
Perhaps y can send them directly to my eMail box (like y did in past)

Jürgen

**Comment by LocutusOfPenguin** [comment] 2016-11-12 12:32
Hi Luigi,

sure...I would be glad, if y provide some italian (voice)!!!

This must be in ogg format, and take a look at "talker/voices/en/al" 
what we need.


Perhaps y can also think about to translate the menu to italian? ;-)
y can take a look here:
https://docs.google.com/spreadsheets/d/1x5yFPOq0aPl0y0tzbcdZJj7RPYTy9VefqAdkCQwEoFs/edit#gid=0
Its abit outdated (v063), but mainly ok...the problem with google 
translate is , its not take into account the chess stuff.
For example google translates "Zug" (de) to "train(en)" but "Zug" could 
be "train" or "move" ...here "move" is right ;-)

Yours,
Jürgen

P.S. i just got the last (missing) voices from the austria kid....So, 
(german) with austria dialect is almost ready (for sure, can have more 
people for each language).



Am 12.11.2016 11:29 schrieb Albireo54:

**Comment by Albireo54** [comment] 2016-11-12 13:45
I will be glad to translate the menu in Italian so please, would you like to give me the write permissions, because the google document is in read-only. When I will be ready with the voices (ogg format) I will write to you attaching the audio files.

Thank you.

Luigi

 

Da: Jürgen Précour [mailto:notifications@github.com] 
Inviato: sabato 12 novembre 2016 13:32
A: jromang/picochess <picochess@noreply.github.com>
Cc: Albireo54 <lvogli@tin.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [jromang/picochess] Play halts after few moves when using USB board (#218)

 

Hi Luigi,

sure...I would be glad, if y provide some italian (voice)!!!

This must be in ogg format, and take a look at "talker/voices/en/al" 
what we need.


Perhaps y can also think about to translate the menu to italian? ;-)
y can take a look here:
 <https://docs.google.com/spreadsheets/d/1x5yFPOq0aPl0y0tzbcdZJj7RPYTy9VefqAdkCQwEoFs/edit#gid=0> https://docs.google.com/spreadsheets/d/1x5yFPOq0aPl0y0tzbcdZJj7RPYTy9VefqAdkCQwEoFs/edit#gid=0
Its abit outdated (v063), but mainly ok...the problem with google 
translate is , its not take into account the chess stuff.
For example google translates "Zug" (de) to "train(en)" but "Zug" could 
be "train" or "move" ...here "move" is right ;-)

Yours,
Jürgen

P.S. i just got the last (missing) voices from the austria kid....So, 
(german) with austria dialect is almost ready (for sure, can have more 
people for each language).



Am 12.11.2016 11:29 schrieb Albireo54:

**Comment by Albireo54** [comment] 2016-11-12 15:53
Hi Jürgen,

attached you will find the lu.zip with the ‘lu’ folder containing the complete italian voices translation, I hope it works ok, I follow the same encoding setup as for the ‘al’ voices (44100 Hz Mono, 32 bit  -  ogg format).

Good evening.

Luigi

 

Da: Jürgen Précour [mailto:notifications@github.com] 
Inviato: sabato 12 novembre 2016 13:32
A: jromang/picochess <picochess@noreply.github.com>
Cc: Albireo54 <lvogli@tin.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [jromang/picochess] Play halts after few moves when using USB board (#218)

 

Hi Luigi,

sure...I would be glad, if y provide some italian (voice)!!!

This must be in ogg format, and take a look at "talker/voices/en/al" 
what we need.


Perhaps y can also think about to translate the menu to italian? ;-)
y can take a look here:
 <https://docs.google.com/spreadsheets/d/1x5yFPOq0aPl0y0tzbcdZJj7RPYTy9VefqAdkCQwEoFs/edit#gid=0> https://docs.google.com/spreadsheets/d/1x5yFPOq0aPl0y0tzbcdZJj7RPYTy9VefqAdkCQwEoFs/edit#gid=0
Its abit outdated (v063), but mainly ok...the problem with google 
translate is , its not take into account the chess stuff.
For example google translates "Zug" (de) to "train(en)" but "Zug" could 
be "train" or "move" ...here "move" is right ;-)

Yours,
Jürgen

P.S. i just got the last (missing) voices from the austria kid....So, 
(german) with austria dialect is almost ready (for sure, can have more 
people for each language).



Am 12.11.2016 11:29 schrieb Albireo54:

**Comment by LocutusOfPenguin** [comment] 2016-11-12 20:44
sorry no attachment
Jürgen

**Comment by Albireo54** [comment] 2016-11-12 22:17
Sorry, I attached it, anyway I post the .zip file also in your google page

Luigi

 

Da: Jürgen Précour [mailto:notifications@github.com] 
Inviato: sabato 12 novembre 2016 21:44
A: jromang/picochess <picochess@noreply.github.com>
Cc: Albireo54 <lvogli@tin.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [jromang/picochess] Play halts after few moves when using USB board (#218)

 

sorry no attachment
Jürgen

**Comment by LocutusOfPenguin** [comment] 2016-11-13 07:32
Hi Luigi,

pushed yr files to jromang/master...molte grazie!
I guess attachments are not transmitted over github. So, if y send yr eMail to a github adr, its ignored.
Jürgen

**Comment by Albireo54** [comment] 2016-11-13 08:48
Hi Jürgen,

I will never put attachments here, I promise :) I will put them in your google page :)

I would like to translate into italian also the menus if you give to me the write permissions here :

 <https://docs.google.com/spreadsheets/d/1x5yFPOq0aPl0y0tzbcdZJj7RPYTy9VefqAdkCQwEoFs/edit#gid=0> https://docs.google.com/spreadsheets/d/1x5yFPOq0aPl0y0tzbcdZJj7RPYTy9VefqAdkCQwEoFs/edit#gid=0

Thank you.

Have a great day.

Luigi

 

Da: Jürgen Précour [mailto:notifications@github.com] 
Inviato: domenica 13 novembre 2016 08:33
A: jromang/picochess <picochess@noreply.github.com>
Cc: Albireo54 <lvogli@tin.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [jromang/picochess] Play halts after few moves when using USB board (#218)

 

Hi Luigi,

pushed yr files to jromang/master...molte grazie!
I guess attachments are not transmitted over github. So, if y send yr eMail to a github adr, its ignored.
Jürgen

**Comment by LocutusOfPenguin** [comment] 2016-11-13 10:51
Hi Luigi,
y can use "LocutusOfPenguin <at    > posteo <point> de".

I need yr eMail adr to give y write access.
Jürgen

**Comment by Albireo54** [comment] 2016-11-13 10:57
Hi Jurgen,

my email is   <mailto:lvogli@tin.it> lvogli@tin.it

Luigi

 

 

Da: Jürgen Précour [mailto:notifications@github.com] 
Inviato: domenica 13 novembre 2016 11:51
A: jromang/picochess <picochess@noreply.github.com>
Cc: Albireo54 <lvogli@tin.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [jromang/picochess] Play halts after few moves when using USB board (#218)

 

Hi Luigi,
y can use "LocutusOfPenguin posteo de".

I need yr eMail adr to give y write access.
Jürgen

**Comment by Albireo54** [comment] 2016-11-14 12:53
Hi Jurgen,

I wonder if you got my this morning email @ posteo de

Luigi

 

Da: Jürgen Précour [mailto:notifications@github.com] 
Inviato: domenica 13 novembre 2016 11:51
A: jromang/picochess <picochess@noreply.github.com>
Cc: Albireo54 <lvogli@tin.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [jromang/picochess] Play halts after few moves when using USB board (#218)

 

Hi Luigi,
y can use "LocutusOfPenguin posteo de".

I need yr eMail adr to give y write access.
Jürgen

**Comment by LocutusOfPenguin** [comment] 2016-11-18 14:23
since the v0.79 with its newest updates (=bugfixes) should solve the voice problem....
i wonder if someone here still have any problems (with voice, or freeze....)
Keep in mind, that maybe y need to install "vorbis-tools" to get a non-stopping-voice (see forum)

This issue is abit "poluted" ;-) by voice - should be better discussed here:
https://github.com/jromang/picochess/issues/154

Anyway, im not the biggest fan of >30 messages issue readings.  Perhaps if someone still has a problem open a new issue, or post here shortly ...i prefer to close this issue.

Thanks,
Jürgen

**Comment by Albireo54** [comment] 2016-11-18 22:00
Hi Jürgen,
I tested your dgt-test 0.79 version and the voice is OK (after installing the vorbis drivers) :)
Is the jromang/master not yet updated to your dgt-test environment, isn't it ?

**Comment by LocutusOfPenguin** [comment] 2016-11-18 22:38
Hi,
jromang/master & LocutusOfPenguin/master are ahead of dgt-test. Both are up-to-date.
Please change yr branch back to master "git checkout master"..."dgt-test" will be deleted soon anyway.

**Comment by Albireo54** [comment] 2016-11-19 07:39
Hi Juergen,
Thank you
Luigi

**Comment by LocutusOfPenguin** [comment] 2016-11-22 13:09
as i said, the dgt-test is deleted..and i began to work on "serial" branch with its goal to reach an "error tolerant serial connection" (in case the serial is somehow broken - like these >1k messages Luigi had).

I'm not sure, that gonna solve this old serial boards problem but since noone answered my last call, i guess its solved anyway, aehm ;-)

**Comment by Albireo54** [comment] 2016-11-23 07:07
Hi Juergen,

last few days I do not have the chance to play w/ picochess, I think if y will solve the serial boards problem it will be great :)

Have a nice day

Luigi

Da: Jürgen Précour [mailto:notifications@github.com] 
Inviato: martedì 22 novembre 2016 14:09
A: jromang/picochess <picochess@noreply.github.com>
Cc: Albireo54 <lvogli@tin.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [jromang/picochess] Play halts after few moves when using USB board (#218)

 

as i said, the dgt-test is deleted..and i began to work on "serial" branch with its goal to reach an "error tolerant serial connection" (in case the serial is somehow broken - like these >1k messages Luigi had).

I'm not sure, that gonna solve this old serial boards problem but since noone answered my last call, i guess its solved anyway, aehm ;-)

**Comment by LocutusOfPenguin** [comment] 2016-11-23 07:29
Hi Luigi,

sure. But my problem is: i don't have such troublesome board/serial connection.
I checked this branch for me, but there is no difference - both are working ;-)

Y might help me and checkout my "serial" branch , and see if that's working for y. I'm esp interested to see any warnings in log file like this (new) "ignore collected message..."

Messages with length > 64 shouldn't happen (anymore)...they are a sign for a serial error transmit.

Jürgen

**Comment by Albireo54** [comment] 2016-11-23 14:39
Hi Jürgen,
For sure I will give a try to your serial branch and I will keep informed :)
I will post a log of an entire game.
Luigi

Inviato da iPad

**Comment by LocutusOfPenguin** [comment] 2016-12-01 12:11
i merged (&deleted) my "serial" branch to my master.
@Albireo54 please use "git checkout master" (& "git pull") to be up-to-date again.

As said, i tried to find error messages from old dgt board versions and correct them as far its possible.
Finally, this issue is closed now (see my comment 13d, 9d before).
If someone still have problems, open a NEW issue.

Jürgen

**Closed by LocutusOfPenguin** 2016-12-01 12:11 UTC
Labels: bug
